server:
  port: 8088
camelsimple:
  api:
    path: /camel
  route:
    path: /route/dev/
camel:
  springboot:
    name: CamelSimple
management:
  port: 8088
  security:
    enabled: false
endpoints:
  enabled: true
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
spring:
  application:
    name: camelboot2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  h2:
    console:
      enabled: true
in3in2route:
  from: file://C:/in3/?charset=utf-8
  toUri1: file://C:/in2A1/
  toUri2: file://C:/in2B/
in5ftproute:
  from: file://C:/in5/?charset=utf-8
  toUri1: ftp://dlpuser@dlptest.com@ftp.dlptest.com/upload?password=3D6XZV9MKdhM5fF&ftpClient.dataTimeout=30000
  
resources:
  extract:
    dir: /route/dev/  
      